---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gitops-llm-dev

resources:
  - ../../infra/base

labels:
  - pairs:
      app.kubernetes.io/part-of: gitops-llm-paper
      app.kubernetes.io/environment: dev
      app.kubernetes.io/managed-by: kustomize

namePrefix: dev-

patches:
  - path: patch-certmgr-controller.yaml
  - path: patch-certmgr-webhook.yaml
  - path: patch-certmgr-cainjector.yaml
  - path: patch-external-secrets.yaml
