apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: gitops-llm-platform
  labels:
    app.kubernetes.io/part-of: gitops-llm-paper
spec:
  template:
    spec:
      containers:
      - name: minio
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
